language: java

jdk:
  - oraclejdk8

script: ant build

addons:
  apt:
    packages:
      - openjdk-6-jdk

# safelist
branches:
  only:
  - master

before_install:
  - cd Implementation\ and\ Testing/


